services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
      - var_data:/var/www/html/var
    networks:
      - app

  nginx:
    image: nginx:stable
    container_name: nginx_symfony
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
    networks:
      - app

volumes:
  var_data:

networks:
  app:
    driver: bridge