services:
  database:
    image: postgres:16
    container_name: pickle_pg
    environment:
      POSTGRES_USER: ricky_admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: pickle_jar
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - app

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app

  nginx:
    image: nginx:stable
    container_name: nginx_symfony
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony
    networks:
      - app

volumes:
  database_data:

networks:
  app:
    driver: bridge